### ISSUE TITLE
Suppor of formulas with "\[ ... \]" etc.

### ISSUE THREAD

**Issue by Ivanx32** [drgulevich/gtexfix#2]
It seems that formulas like
\\[
   S_{i} = \frac{\V_i \big[\E_{\unsim i} (f (\xb) | x_i) \big]} {\V_{\mu} [f]}, \; \; i = 1, \ldots, n, \;
\\]
are not supported.

In addition, google also translates and distorts expressions like "\section", "\subsection", etc.

**Comment by drgulevich** [comment]
Thanks. Actually, the treatment of \section and \subsection is already implemented in the last versions and I will do \\[ ... \\] in the next update.

**Comment by Ivanx32** [comment]
I'd also like to mention an extra space after translation,  e.g. "\section {Введение}".
In some editors this may lead to incorrect bahaviour.
